import { serve } from "bun";
import { Hono } from "hono";
import { cors } from 'hono/cors'
import PocketBase from 'pocketbase';



import testRouter from "./routes/test.js";
import { DICE_LETTERS } from "./constants.js"

const pb = new PocketBase('http://127.0.0.1:8090');

const app = new Hono();
let lastUpdatedDate = new Date();
let code = "";

app.get("/", (c) => {
  return c.text("Hello, World!");
});



/**
 * Endpoint for retrieving a daily code.
 * 
 * The code is generated by randomly selecting a letter from each group in DICE_LETTERS.
 * If the current date in EST is different from the last updated date or the code is empty, a new code is generated.
 * 
 * The code is then returned in the response.
 * 
 * @param {Object} c - The RequestContext object.
 * @returns {Object} - The Response object with the generated code.
 */
app.get("/dailycode", (c) => {

  // Get the current date in EST
  const currentDate = new Date();
  const currentDateEST = new Date(currentDate.toLocaleString("en-US", {timeZone: "America/New_York"}));

  // If the current date in EST is different from the last updated date or the code is empty
  if ((currentDateEST.getDate() !== lastUpdatedDate.getDate()) || code === "") {
    
    // Generate a new code by randomly selecting a letter from each group in DICE_LETTERS
    for (let index = 0; index < DICE_LETTERS.length; index++) {
      const possibleLetters = DICE_LETTERS[index];
      const randomIndex = Math.floor(Math.random() * possibleLetters.length);
      
      code += possibleLetters[randomIndex];
    }

    // Update the last updated date
    lastUpdatedDate = currentDate;
  }

  // Return the generated code
  return c.text(code);

});

app.get("/register", async (c) => {

  const formData = await c.req.parseBody()
  const username = formData.get('username')
  const email = formData.get('email')
  const password = formData.get('password')

  body = {
    username: username,
    email: email,
    password: password
  }

  try {
    await locals.pb.collection('users').create(body);
    // (optional) send an email verification request
    // await locals.pb.collection('users').requestVerification(body.email);
  } catch (err) {
    console.log('Error: ', err);
    throw error(500, 'Something went wrong');
  }

  throw redirect(303, '/login');

  return c.text("TEST ROUTE WORKS!");
});


app.use(
  '/login',
  cors({
    origin: ['http://localhost:5173'],
  })
)


app.post("/login", async (c) => {

  const formData = await c.req.json()
  // const username = formData.get('username')
  // const email = formData.get('email')
  // const password = formData.get('password')

  // body = {
  //   username: username,
  //   email: email,
  //   password: password
  // }

  console.log(formData);

  return c.text("TEST LOGIN WORKS!");




  // try {
  //   let authData = await locals.pb.collection('users').authWithPassword(email, password);
  //   // if (!locals.pb?.authStore?.model?.verified) {
  //   // 	locals.pb.authStore.clear();
  //   // 	return {
  //   // 		notVerified: true
  //   // 	};
  //   // }
  //         // throw redirect(303, '/');
  // } catch (err) {
  //   console.log(err);

  //   if (err?.data?.code == 400) {
  //     console.log("POGGERS");
  //     return {
  //       notVerified: true
  //     };
  //   } else {
  //     console.log('Error: ', err);
  //     throw error(500, 'Something went wrong logging in');
  //   }
  // }

  // throw redirect(303, '/');

})

app.use(
  '/getLeaderboard',
  cors({
    origin: ['http://localhost:5173'],
  })
)

app.get("/getLeaderboard", async (c) => {
  let leaderboard = []
  let records = await pb.collection('solutions').getList(1, 5, {
      sort: '-length',
  });

  let items = records.items
  items.forEach(item => {
      leaderboard.push({username: item.username, longestWord: item.longestWord, length: item.length})
  });
  console.log(leaderboard)

  return c.json({
    props: {
      leaderboard: leaderboard,
    },
  });
})

app.use(
  '/putSolution',
  cors({
    origin: ['http://localhost:5173'],
  })
)

app.post("/putSolution", async (c) => {

  const formData = await c.req.json()

  const longestWord = formData.longestWord
  const length = formData.length



  const id = "prepmlt8t7yf6ko"
  const username = "hublove"

  try {
      // store logged in user/id on page and send it with every request
      const record = await pb.collection('solutions').getOne(id, {
      
      });
  } catch (err) {
      console.log(err);

      if (err?.data?.code == 404) {
          
          const data = {
              "id": id,
              "username": username,
              "longestWord": longestWord,
              "length": length
          };
          console.log("==========================================");
          console.log(data);
          console.log("==========================================");
          const record = await pb.collection('solutions').create(data);


      } else {
          console.log('Error: ', err);
          throw err
      }
  }

  
  
  return c.json(longestWord);

})

// how to make a router handler
// https://bun.dev/docs/routing
app.route("/test", testRouter);

Bun.serve({
  fetch: app.fetch,
  port: 8000
});

console.log("Server running on http://localhost:8000");











// // Set CORS headers
// const headers = new Headers({
//   "Access-Control-Allow-Origin": "*", // Allow all domains
//   "Content-Type": "application/json", // Specify the content type
//   "Access-Control-Allow-Methods": "GET, POST, OPTIONS", // Allowed methods
//   "Access-Control-Allow-Headers": "Content-Type, Authorization" // Allowed headers
// });

// // Handle OPTIONS method for preflight requests
// if (request.method === "OPTIONS") {
//   return new Response(null, { headers, status: 204 });
// }

// return new Response(JSON.stringify({ message: "Hello from Bun!" }), { headers, status: 200 });


// // // Example GET endpoint
// // if (request.url.endsWith("/data") && request.method === "GET") {
// // }

// // // Default response if no routes match
// // return new Response("Not Found", { status: 404 });